### ISSUE TITLE
Translate Problems

### ISSUE THREAD

**Issue by ViniciusmDias** [bootstrapbrasil/bootstrapbrasil.github.io#5]
http://getbootstrap.com.br/docs/4.0/getting-started/introduction/

Descubra o Bootstrap, o mais framework mais conhecido do mundo para criar sites responsivos e mobile, comece com o BootstrapCDN e nosso template inicial.

Sugestão de correção
Descubra o Bootstrap, o framework mais conhecido do mundo para criar sites responsivos e mobile, comece com o BootstrapCDN e nosso template inicial.

**Comment by adammacias** [comment]
Boa @ViniciusmDias https://github.com/bootstrapbrasil/bootstrap/commit/187ae7333244c1297fcb576d74b64f166cb6a41f
